# Generated by Django 4.2.2 on 2024-09-24 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_date",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="Введите дату и время начала рассылки",
                        null=True,
                        verbose_name="Дата и время начала рассылки",
                    ),
                ),
                (
                    "next_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата и время следующей отправки рассылки",
                    ),
                ),
                (
                    "last_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Введите дату и время окончания рассылки",
                        null=True,
                        verbose_name="Дата и время окончания рассылки",
                    ),
                ),
                (
                    "intervals",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily", "Ежедневно"),
                            ("weekly", "Еженедельно"),
                            ("monthly", "Ежемесячно"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "mailing_status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("started", "Запущена"),
                            ("completed", "Завершена"),
                        ],
                        default="created",
                        max_length=50,
                        verbose_name="Статус рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ("intervals",),
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_theme",
                    models.CharField(
                        help_text="Введите тему сообщения",
                        max_length=150,
                        verbose_name="Тема сообщения",
                    ),
                ),
                (
                    "message_body",
                    models.TextField(
                        help_text="Введите текст сообщения", verbose_name="Содержание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ("message_theme",),
            },
        ),
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ("email",),
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="MailingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_mailing",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата и время последней попытки",
                    ),
                ),
                (
                    "status_mailing",
                    models.BooleanField(default=True, verbose_name="Статус попытки"),
                ),
                (
                    "mail_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ответ почтового сервера"
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="mailing.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
                "ordering": ("status_mailing",),
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(
                related_name="mailings", to="mailing.client", verbose_name="Клиенты"
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailings",
                to="mailing.message",
                verbose_name="Сообщение",
            ),
        ),
    ]
