# Generated by Django 4.2.2 on 2024-09-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_mailing_intervals_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="mailinglog",
            name="last_mailing",
            field=models.DateTimeField(
                auto_now_add=True,
                null=True,
                verbose_name="Дата и время последней попытки",
            ),
        ),
    ]
