# Generated by Django 4.2.2 on 2024-09-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_client_is_active_alter_mailinglog_last_mailing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="next_date",
        ),
        migrations.AlterField(
            model_name="mailing",
            name="intervals",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Раз в день", "Раз в день"),
                    ("Раз в неделю", "Раз в неделю"),
                    ("Раз в месяц", "Раз в месяц"),
                ],
                max_length=50,
                null=True,
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="mailing_status",
            field=models.CharField(
                choices=[
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                    ("Завершена", "Завершена"),
                ],
                default="created",
                max_length=50,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
