# Generated by Django 4.2.2 on 2024-09-28 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_remove_mailing_next_date_alter_mailing_intervals_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailinglog",
            options={
                "ordering": ("status_mailing",),
                "verbose_name": "Лог",
                "verbose_name_plural": "Логи",
            },
        ),
        migrations.AddField(
            model_name="mailinglog",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing.client",
                verbose_name="клиент рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(to="mailing.client", verbose_name="Клиенты"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="first_date",
            field=models.DateTimeField(
                help_text="Введите дату и время начала рассылки",
                verbose_name="Дата и время начала рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="intervals",
            field=models.CharField(
                choices=[
                    ("Раз в день", "Раз в день"),
                    ("Раз в неделю", "Раз в неделю"),
                    ("Раз в месяц", "Раз в месяц"),
                ],
                max_length=50,
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="last_date",
            field=models.DateTimeField(
                help_text="Введите дату и время окончания рассылки",
                verbose_name="Дата и время окончания рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="mailing_status",
            field=models.CharField(
                choices=[
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                    ("Завершена", "Завершена"),
                ],
                default="Создана",
                max_length=50,
                verbose_name="Статус рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="mailinglog",
            name="last_mailing",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время последней попытки"
            ),
        ),
        migrations.AlterField(
            model_name="mailinglog",
            name="mailing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="mailing.mailing",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AlterField(
            model_name="mailinglog",
            name="status_mailing",
            field=models.BooleanField(verbose_name="статус попытки"),
        ),
    ]
