# Generated by Django 4.2.2 on 2024-09-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_alter_mailinglog_options_mailinglog_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="intervals",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Раз в день", "Раз в день"),
                    ("Раз в неделю", "Раз в неделю"),
                    ("Раз в месяц", "Раз в месяц"),
                ],
                max_length=50,
                null=True,
                verbose_name="Периодичность",
            ),
        ),
    ]
