# Generated by Django 4.2.2 on 2024-09-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0009_client_owner_mailing_owner_mailinglog_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ("intervals",),
                "permissions": [("set_active_status", "Can active mailing")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
